version: '1'

services:
  app:
    build: 
      context: application
    ports:
      - "5000"
    restart: always
    stdin_open: true
    environment:
      - SEED_SERVER=${SEED_SERVER}
      - PUBKEY=${PUBKEY}
      - PRIVKEY=${PRIVKEY}

  nginx:
    image: nginx:latest
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "80:80"