version: '1'

services:
  app:
    build: 
      context: application
    ports:
      - "5000"
    restart: always
    image: matthiasheilmannprivat/udocoin:latest

  nginx:
    image: nginx:latest
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "80:80"